[package]
name = "dmail-identity"
version = "0.1.0"
authors = ["contact <contact@dmail.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "backend",
]